version: '3'
services:
  db:
    image: mysql
    ports:
    - "3307:3306" # host port 3307 links to container port 3306
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=test_docker_db

  web:
    build: .
    ports:
      - "6000:8080" # host port 6000 links to container port 8080
    depends_on:
      - "db"
    links:
      - "db:database"
    environment:
      WAIT_HOSTS: db:3306
      DB_HOST: database # these db_ env variables should match the env variables in mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_DEFAULT: test_docker_db
  