version: '3'
services:
  web:
    build: .
    ports:
      - "6000:8080" # host has port 6000 links to container port 8080
    depends_on:
      - db
  db:
    image: mysql
    ports:
    - "3307:3306" # host has port 3307 links to container port 3306
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=test_docker_db